- name: hello work
  hosts: localhost
  become: yes
  vars:
    Course: "DevOps"
    Trainer: "Sivakumar"
    Duration: "110HRS"
  tasks:
    - name: check variable
      ansible.builtin.debug:
        msg: "hi {{ Course }} {{ Trainer }} {{ Duration }}"
